(define (stream pick-and-place)
  (:stream sample-pose
    :inputs (?b ?r)
    :domain (and (Block ?b) (Region ?r))
    :outputs (?p)
    :certified (and (Pose ?b ?p) (Contained ?b ?p ?r))
  )
  (:stream inverse-kinematics
    :inputs (?b ?p)
    :domain (Pose ?b ?p)
    :outputs (?q)
    :certified (and (Conf ?q) (Kin ?b ?q ?p))
  )
  (:stream collision-free
    :inputs (?b1 ?p1 ?b2 ?p2)
    :domain (and (Pose ?b1 ?p1) (Pose ?b2 ?p2))
    :outputs ()
    :certified (CFree ?p1 ?p2)
  )
)