(define
  (problem strips-mprime-x-9)
  (:domain no-mystery-prime-strips)
  (:objects endingen weil sexau auggen gottenheim wittlingen waldhaus
      kutsche segway elfenrad krankenwagen faschiertes karfiol
      feine-bratwurst halber-hirsch bananenkiste ochsencremesuppe
      grobe-bratwurst fleisch aschenbecher seitenbacher-muesli
      snickers weihnachtsbaum flasche-jaegermeister fuel-0 fuel-1
      fuel-2 fuel-3 fuel-4 capacity-0 capacity-1 capacity-2
      capacity-3)
  (:init
    (at aschenbecher gottenheim)
    (at bananenkiste sexau)
    (at elfenrad wittlingen)
    (at faschiertes weil)
    (at feine-bratwurst sexau)
    (at flasche-jaegermeister waldhaus)
    (at fleisch gottenheim)
    (at grobe-bratwurst sexau)
    (at halber-hirsch sexau)
    (at karfiol weil)
    (at krankenwagen waldhaus)
    (at kutsche weil)
    (at ochsencremesuppe sexau)
    (at segway sexau)
    (at seitenbacher-muesli waldhaus)
    (at snickers waldhaus)
    (at weihnachtsbaum waldhaus)
    (capacity elfenrad capacity-1)
    (capacity krankenwagen capacity-1)
    (capacity kutsche capacity-3)
    (capacity segway capacity-1)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-number capacity-3)
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (capacity-predecessor capacity-2 capacity-3)
    (connected auggen sexau)
    (connected auggen weil)
    (connected endingen waldhaus)
    (connected endingen wittlingen)
    (connected gottenheim weil)
    (connected gottenheim wittlingen)
    (connected sexau auggen)
    (connected sexau waldhaus)
    (connected waldhaus endingen)
    (connected waldhaus sexau)
    (connected weil auggen)
    (connected weil gottenheim)
    (connected wittlingen endingen)
    (connected wittlingen gottenheim)
    (fuel auggen fuel-0)
    (fuel endingen fuel-2)
    (fuel gottenheim fuel-1)
    (fuel sexau fuel-2)
    (fuel waldhaus fuel-4)
    (fuel weil fuel-2)
    (fuel wittlingen fuel-1)
    (fuel-number fuel-0)
    (fuel-number fuel-1)
    (fuel-number fuel-2)
    (fuel-number fuel-3)
    (fuel-number fuel-4)
    (fuel-predecessor fuel-0 fuel-1)
    (fuel-predecessor fuel-1 fuel-2)
    (fuel-predecessor fuel-2 fuel-3)
    (fuel-predecessor fuel-3 fuel-4)
    (location auggen)
    (location endingen)
    (location gottenheim)
    (location sexau)
    (location waldhaus)
    (location weil)
    (location wittlingen)
    (package aschenbecher)
    (package bananenkiste)
    (package faschiertes)
    (package feine-bratwurst)
    (package flasche-jaegermeister)
    (package fleisch)
    (package grobe-bratwurst)
    (package halber-hirsch)
    (package karfiol)
    (package ochsencremesuppe)
    (package seitenbacher-muesli)
    (package snickers)
    (package weihnachtsbaum)
    (vehicle elfenrad)
    (vehicle krankenwagen)
    (vehicle kutsche)
    (vehicle segway))
  (:goal
    (and
      (at karfiol auggen)
      (at snickers gottenheim))))
