(define
  (problem strips-mprime-x-8)
  (:domain no-mystery-prime-strips)
  (:objects muellheim inzlingen merdingen lauchringen endingen
      emmendingen hugstetten riedlingen freiburg kleinkems wittlingen
      bad-bellingen schopfheim guendlingen boetzingen kandern
      bahlingen wollbach motorrad sulki pferdetransport krankenwagen
      fahrrad kutsche moped droschke feuerwehr kuechenmaschine
      martinsgans bananenkiste leipziger-allerlei terrorist fuel-0
      fuel-1 fuel-2 fuel-3 fuel-4 capacity-0 capacity-1 capacity-2
      capacity-3)
  (:init
    (at bananenkiste endingen)
    (at droschke kandern)
    (at fahrrad riedlingen)
    (at feuerwehr bahlingen)
    (at krankenwagen endingen)
    (at kuechenmaschine inzlingen)
    (at kutsche wittlingen)
    (at leipziger-allerlei kleinkems)
    (at martinsgans endingen)
    (at moped bad-bellingen)
    (at motorrad muellheim)
    (at pferdetransport merdingen)
    (at sulki inzlingen)
    (at terrorist kleinkems)
    (capacity droschke capacity-2)
    (capacity fahrrad capacity-2)
    (capacity feuerwehr capacity-3)
    (capacity krankenwagen capacity-1)
    (capacity kutsche capacity-1)
    (capacity moped capacity-3)
    (capacity motorrad capacity-2)
    (capacity pferdetransport capacity-2)
    (capacity sulki capacity-3)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-number capacity-3)
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (capacity-predecessor capacity-2 capacity-3)
    (connected bad-bellingen guendlingen)
    (connected bad-bellingen inzlingen)
    (connected bad-bellingen kandern)
    (connected bahlingen kandern)
    (connected bahlingen kleinkems)
    (connected boetzingen guendlingen)
    (connected boetzingen hugstetten)
    (connected emmendingen endingen)
    (connected emmendingen inzlingen)
    (connected emmendingen muellheim)
    (connected endingen emmendingen)
    (connected endingen lauchringen)
    (connected endingen muellheim)
    (connected freiburg kleinkems)
    (connected freiburg schopfheim)
    (connected guendlingen bad-bellingen)
    (connected guendlingen boetzingen)
    (connected hugstetten boetzingen)
    (connected hugstetten riedlingen)
    (connected inzlingen bad-bellingen)
    (connected inzlingen emmendingen)
    (connected inzlingen merdingen)
    (connected kandern bad-bellingen)
    (connected kandern bahlingen)
    (connected kleinkems bahlingen)
    (connected kleinkems freiburg)
    (connected lauchringen endingen)
    (connected lauchringen merdingen)
    (connected lauchringen muellheim)
    (connected merdingen inzlingen)
    (connected merdingen lauchringen)
    (connected muellheim emmendingen)
    (connected muellheim endingen)
    (connected muellheim lauchringen)
    (connected riedlingen hugstetten)
    (connected riedlingen wittlingen)
    (connected schopfheim freiburg)
    (connected schopfheim wollbach)
    (connected wittlingen riedlingen)
    (connected wittlingen wollbach)
    (connected wollbach schopfheim)
    (connected wollbach wittlingen)
    (fuel bad-bellingen fuel-1)
    (fuel bahlingen fuel-3)
    (fuel boetzingen fuel-1)
    (fuel emmendingen fuel-4)
    (fuel endingen fuel-0)
    (fuel freiburg fuel-1)
    (fuel guendlingen fuel-1)
    (fuel hugstetten fuel-3)
    (fuel inzlingen fuel-3)
    (fuel kandern fuel-2)
    (fuel kleinkems fuel-3)
    (fuel lauchringen fuel-1)
    (fuel merdingen fuel-0)
    (fuel muellheim fuel-0)
    (fuel riedlingen fuel-2)
    (fuel schopfheim fuel-1)
    (fuel wittlingen fuel-0)
    (fuel wollbach fuel-2)
    (fuel-number fuel-0)
    (fuel-number fuel-1)
    (fuel-number fuel-2)
    (fuel-number fuel-3)
    (fuel-number fuel-4)
    (fuel-predecessor fuel-0 fuel-1)
    (fuel-predecessor fuel-1 fuel-2)
    (fuel-predecessor fuel-2 fuel-3)
    (fuel-predecessor fuel-3 fuel-4)
    (location bad-bellingen)
    (location bahlingen)
    (location boetzingen)
    (location emmendingen)
    (location endingen)
    (location freiburg)
    (location guendlingen)
    (location hugstetten)
    (location inzlingen)
    (location kandern)
    (location kleinkems)
    (location lauchringen)
    (location merdingen)
    (location muellheim)
    (location riedlingen)
    (location schopfheim)
    (location wittlingen)
    (location wollbach)
    (package bananenkiste)
    (package kuechenmaschine)
    (package leipziger-allerlei)
    (package martinsgans)
    (package terrorist)
    (vehicle droschke)
    (vehicle fahrrad)
    (vehicle feuerwehr)
    (vehicle krankenwagen)
    (vehicle kutsche)
    (vehicle moped)
    (vehicle motorrad)
    (vehicle pferdetransport)
    (vehicle sulki))
  (:goal
    (and
      (at bananenkiste bad-bellingen))))
