(define
  (problem strips-mprime-x-14)
  (:domain no-mystery-prime-strips)
  (:objects bad-bellingen loerrach haltingen emmendingen gottenheim
      brombach schallstadt inzlingen tumringen schopfheim wittlingen
      lauchringen waldhaus denzlingen freiburg waldkirch merdingen
      weil kandern koendringen guendlingen moped kutsche fahrrad
      trollwagen feuerwehr droschke auto ICE krankenwagen fleisch
      ochsencremesuppe gimp feine-bratwurst terrorist zamomin
      wensleydale zehn-nackte-friseusen karfiol neujahrsbrezel
      fernseher feinkost-bratling strunkbolzen kaesebaellchen
      flasche-jaegermeister faschiertes weihnachtsbaum schlagobers
      kaesefondue bananenkiste tuete-pommes donnerkiesel
      doener-mit-scharf gruenkohl kapselheber snickers osterei radio
      grobe-bratwurst halbgefrorenes nichts taschenrechner kiste-bier
      fussball broiler zuckerstange aschenbecher saumagen
      seitenbacher-muesli leipziger-allerlei kuechenmaschine twix
      pinkel pfingstochse fuel-0 fuel-1 fuel-2 fuel-3 fuel-4 fuel-5
      capacity-0 capacity-1 capacity-2 capacity-3)
  (:init
    (at ICE koendringen)
    (at aschenbecher weil)
    (at auto weil)
    (at bananenkiste schopfheim)
    (at broiler waldkirch)
    (at doener-mit-scharf wittlingen)
    (at donnerkiesel wittlingen)
    (at droschke freiburg)
    (at fahrrad haltingen)
    (at faschiertes inzlingen)
    (at feine-bratwurst loerrach)
    (at feinkost-bratling schallstadt)
    (at fernseher gottenheim)
    (at feuerwehr schopfheim)
    (at flasche-jaegermeister inzlingen)
    (at fleisch bad-bellingen)
    (at fussball waldkirch)
    (at gimp loerrach)
    (at grobe-bratwurst waldhaus)
    (at gruenkohl wittlingen)
    (at halbgefrorenes waldhaus)
    (at kaesebaellchen inzlingen)
    (at kaesefondue schopfheim)
    (at kapselheber lauchringen)
    (at karfiol emmendingen)
    (at kiste-bier waldkirch)
    (at krankenwagen guendlingen)
    (at kuechenmaschine koendringen)
    (at kutsche loerrach)
    (at leipziger-allerlei kandern)
    (at moped bad-bellingen)
    (at neujahrsbrezel emmendingen)
    (at nichts waldhaus)
    (at ochsencremesuppe loerrach)
    (at osterei lauchringen)
    (at pfingstochse guendlingen)
    (at pinkel guendlingen)
    (at radio waldhaus)
    (at saumagen kandern)
    (at schlagobers tumringen)
    (at seitenbacher-muesli kandern)
    (at snickers lauchringen)
    (at strunkbolzen inzlingen)
    (at taschenrechner waldkirch)
    (at terrorist haltingen)
    (at trollwagen emmendingen)
    (at tuete-pommes schopfheim)
    (at twix guendlingen)
    (at weihnachtsbaum tumringen)
    (at wensleydale haltingen)
    (at zamomin haltingen)
    (at zehn-nackte-friseusen emmendingen)
    (at zuckerstange weil)
    (capacity ICE capacity-2)
    (capacity auto capacity-3)
    (capacity droschke capacity-2)
    (capacity fahrrad capacity-3)
    (capacity feuerwehr capacity-3)
    (capacity krankenwagen capacity-3)
    (capacity kutsche capacity-2)
    (capacity moped capacity-1)
    (capacity trollwagen capacity-2)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-number capacity-3)
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (capacity-predecessor capacity-2 capacity-3)
    (connected bad-bellingen emmendingen)
    (connected bad-bellingen gottenheim)
    (connected brombach freiburg)
    (connected brombach haltingen)
    (connected brombach loerrach)
    (connected denzlingen waldhaus)
    (connected denzlingen wittlingen)
    (connected emmendingen bad-bellingen)
    (connected emmendingen schallstadt)
    (connected emmendingen wittlingen)
    (connected freiburg brombach)
    (connected freiburg merdingen)
    (connected freiburg tumringen)
    (connected freiburg waldkirch)
    (connected gottenheim bad-bellingen)
    (connected gottenheim haltingen)
    (connected guendlingen koendringen)
    (connected guendlingen merdingen)
    (connected guendlingen weil)
    (connected haltingen brombach)
    (connected haltingen gottenheim)
    (connected inzlingen schopfheim)
    (connected inzlingen tumringen)
    (connected kandern koendringen)
    (connected kandern waldkirch)
    (connected koendringen guendlingen)
    (connected koendringen kandern)
    (connected koendringen merdingen)
    (connected koendringen waldkirch)
    (connected lauchringen schopfheim)
    (connected lauchringen tumringen)
    (connected loerrach brombach)
    (connected loerrach schallstadt)
    (connected merdingen freiburg)
    (connected merdingen guendlingen)
    (connected merdingen koendringen)
    (connected merdingen weil)
    (connected schallstadt emmendingen)
    (connected schallstadt loerrach)
    (connected schopfheim inzlingen)
    (connected schopfheim lauchringen)
    (connected schopfheim wittlingen)
    (connected tumringen freiburg)
    (connected tumringen inzlingen)
    (connected tumringen lauchringen)
    (connected tumringen waldhaus)
    (connected tumringen wittlingen)
    (connected waldhaus denzlingen)
    (connected waldhaus tumringen)
    (connected waldkirch freiburg)
    (connected waldkirch kandern)
    (connected waldkirch koendringen)
    (connected weil guendlingen)
    (connected weil merdingen)
    (connected wittlingen denzlingen)
    (connected wittlingen emmendingen)
    (connected wittlingen schopfheim)
    (connected wittlingen tumringen)
    (fuel bad-bellingen fuel-4)
    (fuel brombach fuel-5)
    (fuel denzlingen fuel-1)
    (fuel emmendingen fuel-2)
    (fuel freiburg fuel-5)
    (fuel gottenheim fuel-5)
    (fuel guendlingen fuel-2)
    (fuel haltingen fuel-5)
    (fuel inzlingen fuel-1)
    (fuel kandern fuel-1)
    (fuel koendringen fuel-0)
    (fuel lauchringen fuel-2)
    (fuel loerrach fuel-2)
    (fuel merdingen fuel-2)
    (fuel schallstadt fuel-1)
    (fuel schopfheim fuel-3)
    (fuel tumringen fuel-3)
    (fuel waldhaus fuel-3)
    (fuel waldkirch fuel-2)
    (fuel weil fuel-5)
    (fuel wittlingen fuel-3)
    (fuel-number fuel-0)
    (fuel-number fuel-1)
    (fuel-number fuel-2)
    (fuel-number fuel-3)
    (fuel-number fuel-4)
    (fuel-number fuel-5)
    (fuel-predecessor fuel-0 fuel-1)
    (fuel-predecessor fuel-1 fuel-2)
    (fuel-predecessor fuel-2 fuel-3)
    (fuel-predecessor fuel-3 fuel-4)
    (fuel-predecessor fuel-4 fuel-5)
    (location bad-bellingen)
    (location brombach)
    (location denzlingen)
    (location emmendingen)
    (location freiburg)
    (location gottenheim)
    (location guendlingen)
    (location haltingen)
    (location inzlingen)
    (location kandern)
    (location koendringen)
    (location lauchringen)
    (location loerrach)
    (location merdingen)
    (location schallstadt)
    (location schopfheim)
    (location tumringen)
    (location waldhaus)
    (location waldkirch)
    (location weil)
    (location wittlingen)
    (package aschenbecher)
    (package bananenkiste)
    (package broiler)
    (package doener-mit-scharf)
    (package donnerkiesel)
    (package faschiertes)
    (package feine-bratwurst)
    (package feinkost-bratling)
    (package fernseher)
    (package flasche-jaegermeister)
    (package fleisch)
    (package fussball)
    (package gimp)
    (package grobe-bratwurst)
    (package gruenkohl)
    (package halbgefrorenes)
    (package kaesebaellchen)
    (package kaesefondue)
    (package kapselheber)
    (package karfiol)
    (package kiste-bier)
    (package kuechenmaschine)
    (package leipziger-allerlei)
    (package neujahrsbrezel)
    (package nichts)
    (package ochsencremesuppe)
    (package osterei)
    (package pfingstochse)
    (package pinkel)
    (package radio)
    (package saumagen)
    (package schlagobers)
    (package seitenbacher-muesli)
    (package snickers)
    (package strunkbolzen)
    (package taschenrechner)
    (package terrorist)
    (package tuete-pommes)
    (package twix)
    (package weihnachtsbaum)
    (package wensleydale)
    (package zamomin)
    (package zehn-nackte-friseusen)
    (package zuckerstange)
    (vehicle ICE)
    (vehicle auto)
    (vehicle droschke)
    (vehicle fahrrad)
    (vehicle feuerwehr)
    (vehicle krankenwagen)
    (vehicle kutsche)
    (vehicle moped)
    (vehicle trollwagen))
  (:goal
    (and
      (at leipziger-allerlei emmendingen)
      (at saumagen emmendingen))))
