(define
  (problem strips-mprime-x-2)
  (:domain no-mystery-prime-strips)
  (:objects merdingen freiburg auggen waldhaus guendlingen breisach
      kandern krankenwagen feuerwehr pferdetransport sulki zamomin
      halbgefrorenes apfel wensleydale fernseher pfingstochse fleisch
      twix feine-bratwurst bananenkiste zuckerstange kiste-bier
      seitenbacher-muesli osterei radio nichts kaesebaellchen pinkel
      zehn-nackte-friseusen karfiol fuel-0 fuel-1 fuel-2 fuel-3 fuel-4
      capacity-0 capacity-1 capacity-2 capacity-3)
  (:init
    (at apfel merdingen)
    (at bananenkiste auggen)
    (at feine-bratwurst auggen)
    (at fernseher merdingen)
    (at feuerwehr waldhaus)
    (at fleisch freiburg)
    (at halbgefrorenes merdingen)
    (at kaesebaellchen kandern)
    (at karfiol kandern)
    (at kiste-bier auggen)
    (at krankenwagen freiburg)
    (at nichts breisach)
    (at osterei waldhaus)
    (at pferdetransport guendlingen)
    (at pfingstochse freiburg)
    (at pinkel kandern)
    (at radio guendlingen)
    (at seitenbacher-muesli waldhaus)
    (at sulki kandern)
    (at twix freiburg)
    (at wensleydale merdingen)
    (at zamomin merdingen)
    (at zehn-nackte-friseusen kandern)
    (at zuckerstange auggen)
    (capacity feuerwehr capacity-2)
    (capacity krankenwagen capacity-1)
    (capacity pferdetransport capacity-2)
    (capacity sulki capacity-3)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-number capacity-3)
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (capacity-predecessor capacity-2 capacity-3)
    (connected auggen breisach)
    (connected auggen kandern)
    (connected auggen merdingen)
    (connected auggen waldhaus)
    (connected breisach auggen)
    (connected breisach freiburg)
    (connected breisach kandern)
    (connected freiburg breisach)
    (connected freiburg guendlingen)
    (connected freiburg merdingen)
    (connected guendlingen freiburg)
    (connected guendlingen merdingen)
    (connected guendlingen waldhaus)
    (connected kandern auggen)
    (connected kandern breisach)
    (connected merdingen auggen)
    (connected merdingen freiburg)
    (connected merdingen guendlingen)
    (connected waldhaus auggen)
    (connected waldhaus guendlingen)
    (fuel auggen fuel-2)
    (fuel breisach fuel-2)
    (fuel freiburg fuel-3)
    (fuel guendlingen fuel-4)
    (fuel kandern fuel-4)
    (fuel merdingen fuel-4)
    (fuel waldhaus fuel-2)
    (fuel-number fuel-0)
    (fuel-number fuel-1)
    (fuel-number fuel-2)
    (fuel-number fuel-3)
    (fuel-number fuel-4)
    (fuel-predecessor fuel-0 fuel-1)
    (fuel-predecessor fuel-1 fuel-2)
    (fuel-predecessor fuel-2 fuel-3)
    (fuel-predecessor fuel-3 fuel-4)
    (location auggen)
    (location breisach)
    (location freiburg)
    (location guendlingen)
    (location kandern)
    (location merdingen)
    (location waldhaus)
    (package apfel)
    (package bananenkiste)
    (package feine-bratwurst)
    (package fernseher)
    (package fleisch)
    (package halbgefrorenes)
    (package kaesebaellchen)
    (package karfiol)
    (package kiste-bier)
    (package nichts)
    (package osterei)
    (package pfingstochse)
    (package pinkel)
    (package radio)
    (package seitenbacher-muesli)
    (package twix)
    (package wensleydale)
    (package zamomin)
    (package zehn-nackte-friseusen)
    (package zuckerstange)
    (vehicle feuerwehr)
    (vehicle krankenwagen)
    (vehicle pferdetransport)
    (vehicle sulki))
  (:goal
    (and
      (at kaesebaellchen merdingen)
      (at nichts merdingen))))
