domains = [
{'description': 'This is the mystery domain with one extra action, the ability to squirt a unit of fuel from any node to a neighboring node, provided the originating node has at least two units. Created by Drew McDermott',
 'ipc': None,
 'name': 'no-mprime',
 'problems': [('no-mprime/domain.pddl', 'no-mprime/prob01.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob02.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob03.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob04.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob05.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob06.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob07.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob08.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob09.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob10.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob11.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob12.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob13.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob14.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob15.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob16.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob17.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob18.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob19.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob20.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob21.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob22.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob23.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob24.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob25.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob26.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob27.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob28.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob29.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob30.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob31.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob32.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob33.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob34.pddl'),
              ('no-mprime/domain.pddl', 'no-mprime/prob35.pddl')]}
]