(define
  (problem strips-mprime-y-5)
  (:domain no-mystery-prime-strips)
  (:objects sexau waldkirch bahlingen breisach wittlingen gottenheim
      sulki trollwagen kuebelwagen ICE kukuruz halbgefrorenes fuel-0
      fuel-1 fuel-2 fuel-3 fuel-4 fuel-5 capacity-0 capacity-1
      capacity-2 capacity-3)
  (:init
    (at ICE gottenheim)
    (at halbgefrorenes gottenheim)
    (at kuebelwagen bahlingen)
    (at kukuruz gottenheim)
    (at sulki sexau)
    (at trollwagen waldkirch)
    (capacity ICE capacity-3)
    (capacity kuebelwagen capacity-2)
    (capacity sulki capacity-3)
    (capacity trollwagen capacity-2)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-number capacity-3)
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (capacity-predecessor capacity-2 capacity-3)
    (connected bahlingen breisach)
    (connected bahlingen gottenheim)
    (connected bahlingen wittlingen)
    (connected breisach bahlingen)
    (connected breisach wittlingen)
    (connected gottenheim bahlingen)
    (connected gottenheim waldkirch)
    (connected sexau waldkirch)
    (connected sexau wittlingen)
    (connected waldkirch gottenheim)
    (connected waldkirch sexau)
    (connected wittlingen bahlingen)
    (connected wittlingen breisach)
    (connected wittlingen sexau)
    (fuel bahlingen fuel-3)
    (fuel breisach fuel-3)
    (fuel gottenheim fuel-0)
    (fuel sexau fuel-0)
    (fuel waldkirch fuel-5)
    (fuel wittlingen fuel-1)
    (fuel-number fuel-0)
    (fuel-number fuel-1)
    (fuel-number fuel-2)
    (fuel-number fuel-3)
    (fuel-number fuel-4)
    (fuel-number fuel-5)
    (fuel-predecessor fuel-0 fuel-1)
    (fuel-predecessor fuel-1 fuel-2)
    (fuel-predecessor fuel-2 fuel-3)
    (fuel-predecessor fuel-3 fuel-4)
    (fuel-predecessor fuel-4 fuel-5)
    (location bahlingen)
    (location breisach)
    (location gottenheim)
    (location sexau)
    (location waldkirch)
    (location wittlingen)
    (package halbgefrorenes)
    (package kukuruz)
    (vehicle ICE)
    (vehicle kuebelwagen)
    (vehicle sulki)
    (vehicle trollwagen))
  (:goal
    (and
      (at halbgefrorenes wittlingen))))
