(define
  (problem strips-mprime-x-6)
  (:domain no-mystery-prime-strips)
  (:objects auggen sexau schallstadt bad-bellingen inzlingen
      hugstetten loerrach waldhaus brombach guendlingen waldkirch
      lauchringen riedlingen denzlingen wittlingen tumringen muellheim
      boetzingen endingen krankenwagen kuebelwagen motorroller segway
      droschke auto kutsche daemonenrikscha feuerwehr ICE moped nichts
      grobe-bratwurst kapselheber pfingstochse flasche-jaegermeister
      feinkost-bratling fussball strunkbolzen wensleydale fuel-0
      fuel-1 fuel-2 fuel-3 fuel-4 fuel-5 fuel-6 capacity-0 capacity-1
      capacity-2 capacity-3)
  (:init
    (at ICE tumringen)
    (at auto waldhaus)
    (at daemonenrikscha riedlingen)
    (at droschke loerrach)
    (at feinkost-bratling waldkirch)
    (at feuerwehr denzlingen)
    (at flasche-jaegermeister brombach)
    (at fussball wittlingen)
    (at grobe-bratwurst bad-bellingen)
    (at kapselheber hugstetten)
    (at krankenwagen auggen)
    (at kuebelwagen sexau)
    (at kutsche guendlingen)
    (at moped muellheim)
    (at motorroller schallstadt)
    (at nichts schallstadt)
    (at pfingstochse loerrach)
    (at segway bad-bellingen)
    (at strunkbolzen boetzingen)
    (at wensleydale endingen)
    (capacity ICE capacity-1)
    (capacity auto capacity-3)
    (capacity daemonenrikscha capacity-3)
    (capacity droschke capacity-1)
    (capacity feuerwehr capacity-3)
    (capacity krankenwagen capacity-1)
    (capacity kuebelwagen capacity-2)
    (capacity kutsche capacity-2)
    (capacity moped capacity-3)
    (capacity motorroller capacity-3)
    (capacity segway capacity-3)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-number capacity-3)
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (capacity-predecessor capacity-2 capacity-3)
    (connected auggen bad-bellingen)
    (connected auggen inzlingen)
    (connected bad-bellingen auggen)
    (connected bad-bellingen schallstadt)
    (connected boetzingen guendlingen)
    (connected boetzingen lauchringen)
    (connected boetzingen muellheim)
    (connected brombach hugstetten)
    (connected brombach inzlingen)
    (connected brombach waldhaus)
    (connected denzlingen endingen)
    (connected denzlingen muellheim)
    (connected denzlingen tumringen)
    (connected endingen denzlingen)
    (connected endingen lauchringen)
    (connected endingen waldkirch)
    (connected guendlingen boetzingen)
    (connected guendlingen waldkirch)
    (connected hugstetten brombach)
    (connected hugstetten loerrach)
    (connected inzlingen auggen)
    (connected inzlingen brombach)
    (connected inzlingen sexau)
    (connected lauchringen boetzingen)
    (connected lauchringen endingen)
    (connected lauchringen muellheim)
    (connected loerrach hugstetten)
    (connected loerrach muellheim)
    (connected loerrach waldhaus)
    (connected muellheim boetzingen)
    (connected muellheim denzlingen)
    (connected muellheim lauchringen)
    (connected muellheim loerrach)
    (connected muellheim wittlingen)
    (connected riedlingen tumringen)
    (connected riedlingen wittlingen)
    (connected schallstadt bad-bellingen)
    (connected schallstadt sexau)
    (connected sexau inzlingen)
    (connected sexau schallstadt)
    (connected tumringen denzlingen)
    (connected tumringen riedlingen)
    (connected waldhaus brombach)
    (connected waldhaus loerrach)
    (connected waldkirch endingen)
    (connected waldkirch guendlingen)
    (connected wittlingen muellheim)
    (connected wittlingen riedlingen)
    (fuel auggen fuel-3)
    (fuel bad-bellingen fuel-4)
    (fuel boetzingen fuel-4)
    (fuel brombach fuel-2)
    (fuel denzlingen fuel-5)
    (fuel endingen fuel-6)
    (fuel guendlingen fuel-3)
    (fuel hugstetten fuel-1)
    (fuel inzlingen fuel-3)
    (fuel lauchringen fuel-2)
    (fuel loerrach fuel-2)
    (fuel muellheim fuel-3)
    (fuel riedlingen fuel-3)
    (fuel schallstadt fuel-1)
    (fuel sexau fuel-0)
    (fuel tumringen fuel-0)
    (fuel waldhaus fuel-1)
    (fuel waldkirch fuel-3)
    (fuel wittlingen fuel-4)
    (fuel-number fuel-0)
    (fuel-number fuel-1)
    (fuel-number fuel-2)
    (fuel-number fuel-3)
    (fuel-number fuel-4)
    (fuel-number fuel-5)
    (fuel-number fuel-6)
    (fuel-predecessor fuel-0 fuel-1)
    (fuel-predecessor fuel-1 fuel-2)
    (fuel-predecessor fuel-2 fuel-3)
    (fuel-predecessor fuel-3 fuel-4)
    (fuel-predecessor fuel-4 fuel-5)
    (fuel-predecessor fuel-5 fuel-6)
    (location auggen)
    (location bad-bellingen)
    (location boetzingen)
    (location brombach)
    (location denzlingen)
    (location endingen)
    (location guendlingen)
    (location hugstetten)
    (location inzlingen)
    (location lauchringen)
    (location loerrach)
    (location muellheim)
    (location riedlingen)
    (location schallstadt)
    (location sexau)
    (location tumringen)
    (location waldhaus)
    (location waldkirch)
    (location wittlingen)
    (package feinkost-bratling)
    (package flasche-jaegermeister)
    (package fussball)
    (package grobe-bratwurst)
    (package kapselheber)
    (package nichts)
    (package pfingstochse)
    (package strunkbolzen)
    (package wensleydale)
    (vehicle ICE)
    (vehicle auto)
    (vehicle daemonenrikscha)
    (vehicle droschke)
    (vehicle feuerwehr)
    (vehicle krankenwagen)
    (vehicle kuebelwagen)
    (vehicle kutsche)
    (vehicle moped)
    (vehicle motorroller)
    (vehicle segway))
  (:goal
    (and
      (at flasche-jaegermeister muellheim)
      (at nichts muellheim))))
