(define
  (problem strips-mprime-x-11)
  (:domain no-mystery-prime-strips)
  (:objects boetzingen riedlingen bahlingen waldkirch gottenheim
      freiburg denzlingen schallstadt fahrrad gimp twix karfiol
      kiste-bier grobe-bratwurst aschenbecher feine-bratwurst pinkel
      fuel-0 fuel-1 fuel-2 fuel-3 fuel-4 fuel-5 capacity-0 capacity-1
      capacity-2)
  (:init
    (at aschenbecher freiburg)
    (at fahrrad bahlingen)
    (at feine-bratwurst denzlingen)
    (at gimp boetzingen)
    (at grobe-bratwurst gottenheim)
    (at karfiol bahlingen)
    (at kiste-bier waldkirch)
    (at pinkel schallstadt)
    (at twix riedlingen)
    (capacity fahrrad capacity-2)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (connected bahlingen denzlingen)
    (connected bahlingen riedlingen)
    (connected bahlingen waldkirch)
    (connected boetzingen freiburg)
    (connected boetzingen riedlingen)
    (connected denzlingen bahlingen)
    (connected denzlingen freiburg)
    (connected freiburg boetzingen)
    (connected freiburg denzlingen)
    (connected freiburg gottenheim)
    (connected freiburg schallstadt)
    (connected gottenheim freiburg)
    (connected gottenheim schallstadt)
    (connected riedlingen bahlingen)
    (connected riedlingen boetzingen)
    (connected schallstadt freiburg)
    (connected schallstadt gottenheim)
    (connected schallstadt waldkirch)
    (connected waldkirch bahlingen)
    (connected waldkirch schallstadt)
    (fuel bahlingen fuel-2)
    (fuel boetzingen fuel-3)
    (fuel denzlingen fuel-3)
    (fuel freiburg fuel-5)
    (fuel gottenheim fuel-4)
    (fuel riedlingen fuel-0)
    (fuel schallstadt fuel-2)
    (fuel waldkirch fuel-1)
    (fuel-number fuel-0)
    (fuel-number fuel-1)
    (fuel-number fuel-2)
    (fuel-number fuel-3)
    (fuel-number fuel-4)
    (fuel-number fuel-5)
    (fuel-predecessor fuel-0 fuel-1)
    (fuel-predecessor fuel-1 fuel-2)
    (fuel-predecessor fuel-2 fuel-3)
    (fuel-predecessor fuel-3 fuel-4)
    (fuel-predecessor fuel-4 fuel-5)
    (location bahlingen)
    (location boetzingen)
    (location denzlingen)
    (location freiburg)
    (location gottenheim)
    (location riedlingen)
    (location schallstadt)
    (location waldkirch)
    (package aschenbecher)
    (package feine-bratwurst)
    (package gimp)
    (package grobe-bratwurst)
    (package karfiol)
    (package kiste-bier)
    (package pinkel)
    (package twix)
    (vehicle fahrrad))
  (:goal
    (and
      (at karfiol gottenheim)
      (at kiste-bier gottenheim))))
