(define
  (problem strips-mprime-x-1)
  (:domain no-mystery-prime-strips)
  (:objects muellheim auggen schopfheim bad-bellingen weil schallstadt
      trollwagen karfiol kiste-bier pinkel fuel-0 fuel-1 fuel-2 fuel-3
      fuel-4 fuel-5 fuel-6 capacity-0 capacity-1 capacity-2
      capacity-3)
  (:init
    (at karfiol muellheim)
    (at kiste-bier schopfheim)
    (at pinkel weil)
    (at trollwagen weil)
    (capacity trollwagen capacity-3)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-number capacity-3)
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (capacity-predecessor capacity-2 capacity-3)
    (connected auggen bad-bellingen)
    (connected auggen muellheim)
    (connected bad-bellingen auggen)
    (connected bad-bellingen weil)
    (connected muellheim auggen)
    (connected muellheim muellheim)
    (connected muellheim schopfheim)
    (connected schallstadt schopfheim)
    (connected schallstadt weil)
    (connected schopfheim muellheim)
    (connected schopfheim schallstadt)
    (connected weil bad-bellingen)
    (connected weil schallstadt)
    (fuel auggen fuel-2)
    (fuel bad-bellingen fuel-6)
    (fuel muellheim fuel-1)
    (fuel schallstadt fuel-3)
    (fuel schopfheim fuel-4)
    (fuel weil fuel-5)
    (fuel-number fuel-0)
    (fuel-number fuel-1)
    (fuel-number fuel-2)
    (fuel-number fuel-3)
    (fuel-number fuel-4)
    (fuel-number fuel-5)
    (fuel-number fuel-6)
    (fuel-predecessor fuel-0 fuel-1)
    (fuel-predecessor fuel-1 fuel-2)
    (fuel-predecessor fuel-2 fuel-3)
    (fuel-predecessor fuel-3 fuel-4)
    (fuel-predecessor fuel-4 fuel-5)
    (fuel-predecessor fuel-5 fuel-6)
    (location auggen)
    (location bad-bellingen)
    (location muellheim)
    (location schallstadt)
    (location schopfheim)
    (location weil)
    (package karfiol)
    (package kiste-bier)
    (package pinkel)
    (vehicle trollwagen))
  (:goal
    (and
      (at pinkel muellheim))))
