(define
  (problem strips-mprime-x-3)
  (:domain no-mystery-prime-strips)
  (:objects weil denzlingen muellheim inzlingen boetzingen koendringen
      waldhaus bahlingen wittlingen hugstetten wollbach segway sulki
      pferdetransport daemonenrikscha schlagobers grobe-bratwurst
      haehnchenbein gruenkohl kukuruz pinkel nichts feinkost-bratling
      fuel-0 fuel-1 fuel-2 fuel-3 fuel-4 capacity-0 capacity-1
      capacity-2)
  (:init
    (at daemonenrikscha wollbach)
    (at feinkost-bratling hugstetten)
    (at grobe-bratwurst inzlingen)
    (at gruenkohl koendringen)
    (at haehnchenbein boetzingen)
    (at kukuruz waldhaus)
    (at nichts wittlingen)
    (at pferdetransport bahlingen)
    (at pinkel bahlingen)
    (at schlagobers weil)
    (at segway weil)
    (at sulki koendringen)
    (capacity daemonenrikscha capacity-2)
    (capacity pferdetransport capacity-2)
    (capacity segway capacity-1)
    (capacity sulki capacity-2)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (connected bahlingen wittlingen)
    (connected bahlingen wollbach)
    (connected boetzingen denzlingen)
    (connected boetzingen inzlingen)
    (connected boetzingen koendringen)
    (connected denzlingen boetzingen)
    (connected denzlingen inzlingen)
    (connected denzlingen muellheim)
    (connected denzlingen weil)
    (connected hugstetten waldhaus)
    (connected hugstetten wittlingen)
    (connected inzlingen boetzingen)
    (connected inzlingen denzlingen)
    (connected koendringen boetzingen)
    (connected koendringen muellheim)
    (connected koendringen weil)
    (connected muellheim denzlingen)
    (connected muellheim koendringen)
    (connected waldhaus hugstetten)
    (connected waldhaus weil)
    (connected waldhaus wollbach)
    (connected weil denzlingen)
    (connected weil koendringen)
    (connected weil waldhaus)
    (connected wittlingen bahlingen)
    (connected wittlingen hugstetten)
    (connected wollbach bahlingen)
    (connected wollbach waldhaus)
    (fuel bahlingen fuel-2)
    (fuel boetzingen fuel-2)
    (fuel denzlingen fuel-2)
    (fuel hugstetten fuel-4)
    (fuel inzlingen fuel-2)
    (fuel koendringen fuel-3)
    (fuel muellheim fuel-0)
    (fuel waldhaus fuel-4)
    (fuel weil fuel-4)
    (fuel wittlingen fuel-1)
    (fuel wollbach fuel-1)
    (fuel-number fuel-0)
    (fuel-number fuel-1)
    (fuel-number fuel-2)
    (fuel-number fuel-3)
    (fuel-number fuel-4)
    (fuel-predecessor fuel-0 fuel-1)
    (fuel-predecessor fuel-1 fuel-2)
    (fuel-predecessor fuel-2 fuel-3)
    (fuel-predecessor fuel-3 fuel-4)
    (location bahlingen)
    (location boetzingen)
    (location denzlingen)
    (location hugstetten)
    (location inzlingen)
    (location koendringen)
    (location muellheim)
    (location waldhaus)
    (location weil)
    (location wittlingen)
    (location wollbach)
    (package feinkost-bratling)
    (package grobe-bratwurst)
    (package gruenkohl)
    (package haehnchenbein)
    (package kukuruz)
    (package nichts)
    (package pinkel)
    (package schlagobers)
    (vehicle daemonenrikscha)
    (vehicle pferdetransport)
    (vehicle segway)
    (vehicle sulki))
  (:goal
    (and
      (at nichts hugstetten))))
