domains = [
{'description': 'Inspired by planetary rovers problems, this domain requires that a collection of rovers navigate a planet surface, finding samples and communicating them back to a lander.',
 'ipc': '2002',
 'name': 'rovers',
 'problems': [('rovers-02/domain.pddl', 'rovers-02/pfile1.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile10.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile11.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile12.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile13.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile14.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile15.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile16.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile17.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile18.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile19.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile2.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile20.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile3.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile4.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile5.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile6.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile7.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile8.pddl'),
              ('rovers-02/domain.pddl', 'rovers-02/pfile9.pddl')]}
]