(define (stream kuka-tamp)
  (:stream sample-pose
    :inputs (?o ?s)
    :domain (Stackable ?o ?s)
    :outputs (?p)
    :certified (and (Pose ?o ?p) (Supported ?o ?p ?s))
  )
  (:stream sample-grasp
    :inputs (?o)
    :domain (Graspable ?o)
    :outputs (?g)
    :certified (Grasp ?o ?g)
  )
  (:stream inverse-kinematics
    :inputs (?r ?o ?p ?g)
    :domain (and (Robot ?r) (Pose ?o ?p) (Grasp ?o ?g))
    :outputs (?q ?t)
    :certified (and (Conf ?r ?q) (Traj ?t)
                    (Kin ?r ?o ?p ?g ?q ?t))
  )
  (:stream plan-motion
    :inputs (?r ?q1 ?q2)
    :domain (and (Conf ?r ?q1) (Conf ?r ?q2) (Robot ?r))
    ;:fluents (AtPose AtConf)
    :outputs (?t)
    :certified (Motion ?r ?q1 ?q2 ?t)
  )
  (:stream plan-pull
    :inputs (?r ?d ?dq1 ?dq2)
    :domain (and (Robot ?r) (Conf ?d ?dq1) (Conf ?d ?dq2) (Door ?d))
    :outputs (?rq1 ?rq2 ?t)
    :certified (and (Conf ?r ?rq1) (Conf ?r ?rq2) (Traj ?t)
                    (Pull ?r ?rq1 ?rq2 ?d ?dq1 ?dq2 ?t))
  )

  ;(:predicate (TrajCollision ?t ?o2 ?p2)
  ;  (and (Traj ?t) (Pose ?o2 ?p2))
  ;)
)